### ISSUE TITLE
Can't build using Pod

### ISSUE THREAD

**Issue by arisbosarge** [shuftipro/iOS-SDK#5]
version 1.0.19

After installing the pod, it says it can't find the ShuftiPro library while building.

**Comment by kingsofteng** [comment]
Can't use 1.0.19 on xCode 12.0.1. It gets crashed.

**Comment by sstigler** [comment]
This is a big issue. It means that I (and I think anyone else using one of Apple's new M1 processors in their computers) cannot develop software using this SDK because the earliest version of Xcode supported by M1 computers is 12.something. Do you have an ETA on a fix for this?

**Comment by shuftipro** [comment]
> version 1.0.19
> 
> After installing the pod, it says it can't find the ShuftiPro library while building.

Kindly know, we have updated the pod. Please try to reinstall it with the latest version.
Note: After installing the pod, make sure you have opened Projectname.xcworkspace file and clean the project as well.

**Comment by shuftipro** [comment]
> Can't use 1.0.19 on xCode 12.0.1. It gets crashed.

This issue needs to be fixed at your end. Please make sure you are using a stable version of Xcode instead of the beta version.
