### ISSUE TITLE
Cannot request success using token authorization method

### ISSUE THREAD

**Issue by moQingTing** [shuftipro/iOS-SDK#6]
# iOS sdk uses the token method to authorize, and the authorization cannot be successful
`authKeys = [
            "auth_type" : "access_token",
            "access_token" : accessToken,
        ]
`
### This token is no problem in the Android SDK, but it is invalid in the iOS SDK.
![image](https://user-images.githubusercontent.com/18046454/144008019-4c911567-eddb-41ba-b17b-a11db6f6c371.png)
# The error is as follows:
![image](https://user-images.githubusercontent.com/18046454/144008380-64a43ccd-2cd7-424a-9813-37416c679035.png)

**Comment by shuftipro** [comment]
The problem has been solved
